Todo
diamond-nicholas/todoList pull request #1
Opened 2021-08-05 04:27 UTC by diamond-nicholas

An advanced todoList that allows users to create projects and different task on the created project

This app does the following:

- User can create a project
- User can create a task under a project
- User can delete completed projects
- User can delete completed task
- User can check task count for incomplete task

2021-08-05 04:51 UTC, mke2111 requested changes
### Hey @diamond-nicholas, 

**This is a great project you have going on, well-done lad**. 

### Well-done 💯 
    1. You have added a clean UI that's easy to navigate.
   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-08-05 04:51 UTC, mke2111 commented on src/app.js
> +/* eslint-disable quotes */
- [ ] Currently, all your code for the app is in this file. You are required to separate all the application logic from the DOM-related stuff. Add new files for creating a new todo, another for creating a new project, another for the DOM manipulation. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png) from Odin)

2021-08-05 04:56 UTC, mke2111 commented on src/app.js
> +/* eslint-disable quotes */
- [ ] A user should be able to edit to-dos that they created. Add this logic to your app.

2021-08-05 05:01 UTC, mke2111 commented on src/app.js
> +const render = () => {
- [ ] Under the my projects section, a default project should exist even after creating new projects.

2021-08-05 05:04 UTC, mke2111 commented on package.json
> +  "scripts": {
- [ ] Add the necessary run command in the package.json file under the scripts.
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```

2021-08-05 05:07 UTC, mke2111 commented on src/app.js
> +function createList(topic) {
- [ ] It is better to use the ES6 arrow functions instead of using the function keywords. Make the changes where necessary for all your functions

2021-08-05 05:09 UTC, mke2111 commented on src/index.js
> +// eslint-disable-next-line quotes
- [ ] This eslint disable can be fixed. Make the required change and ensure not to disable any eslint rules

2021-08-05 05:13 UTC, mke2111 commented on src/app.js
> +/* eslint-disable no-use-before-define */
- [ ] You have disabled quite a number of eslint rules. All these can be fixed such no unused vars indicates that there is a declared variable that you are not using anywhere, no use before define means that you are using a variable before defining it. This simply indicates that all these rules do not have to be disabled. Remember, these rules are here to help you write standard accepted code.

2021-08-10 00:04 UTC, mke2111 requested changes
### Hey @diamond-nicholas, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-08-10 00:10 UTC, mke2111 commented on src/index.js
> +// eslint-disable-next-line quotes
- [ ] One of the few issues left to fix includes eslint disabling. This one, in particular, can be avoided by using single quotes.

2021-08-10 00:11 UTC, mke2111 commented on src/app.js
> +const render = () => {
- [ ] Under my projects section, a default project should exist even after creating new projects. This has not been implemented yet.

2021-08-10 06:27 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested changes. 
Check my comment for a change to be made. Good luck.


### Martin Afani
#### Slack: whiz25

2021-08-10 06:27 UTC, afanimartin commented on src/app.js
> +let lists = JSON.parse(localStorage.getItem(myDom.LOCAL_STORAGE_LIST_KEY)) || [
- Do not disable linter rules. Fix all errors. This was already pointed out in the previous reviews.

2021-08-10 06:56 UTC, afanimartin approved these changes
## Approved 👍🏿 👍🏿 👍🏿 
Change made as requested. Merge and proceed to the next project.

### Martin Afani
#### Slack: whiz25

2021-08-10 07:31 UTC, merged